server:
  port: 9090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 1234
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    
  
      


  mail:
    host: smtp.gmail.com 
    port: 587
    username: jamki89@gmail.com
    password: pawlhacfpabgncbt
    properties: 
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

    
      

      





















