server:
  port: 9090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Subha1234@
    url: jdbc:mysql://localhost:3306/ecomm
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    
  
      


  mail:
    host: smtp.gmail.com 
    port: 587
    username: dsubhajit148@gmail.com
    password: vdytozjncpmctnhi
    properties: 
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

    
      

      





















